### ISSUE TITLE
Create a variation of `HelloSignException` to denote 404s

### ISSUE THREAD

**Issue by cmpaul** [HelloFax/hellosign-java-sdk#45]
Per @mveitas:

It would be nice to introduce a subclass of `HelloSignException` that might be used to denote a resource that was not found

**Comment by mashleyttu** [comment]
I 2nd this request. It would be great if HelloSign could throw different exceptions for different events. For example, a couple of weeks ago when AWS was down our end users couldn't sign documents and we were just displaying a generic issue occurred prompt. It would be great if HelloSign could throw a HelloSignMaintenanceException which we could catch and show the user a more friendly meaningful message.

Thanks for your consideration. Matt

**Comment by Framinus** [comment]
The following exception is thrown for the error message body when a 409 status code is returned: 

Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0 
at org.json.JSONTokener.syntaxError(JSONTokener.java:410) ~[hellosign-java-sdk-4.0.9-jar-with-dependencies.jar!/:?] 
at org.json.JSONObject.<init>(JSONObject.java:179) ~[hellosign-java-sdk-4.0.9-jar-with-dependencies.jar!/:?] 
at org.json.JSONObject.<init>(JSONObject.java:402) ~[hellosign-java-sdk-4.0.9-jar-with-dependencies.jar!/:?] 
at com.hellosign.sdk.http.HttpClient.asJson(HttpClient.java:206) ~[hellosign-java-sdk-4.0.9-jar-with-dependencies.jar!/:?] 
at com.hellosign.sdk.HelloSignClient.createEmbeddedRequest(HelloSignClient.java:797) ~[hellosign-java-sdk-4.0.9-jar-with-dependencies.jar!/:?]
