### ISSUE TITLE
Add support for delegated and downloadable events

### ISSUE THREAD

**Issue by cmpaul** [HelloFax/hellosign-java-sdk#49]
The upcoming release will contain callback event types:

* `signature_request_downloadable`
* `signature_request_delegated`

**Comment by mveitas** [comment]
One side effect with the current SDK is that if you have no deployed the latest version of the SDK, you will get deserialization errors when attempting to read the new `EventType` values. 

```
java.lang.IllegalArgumentException: No enum constant com.hellosign.sdk.resource.support.types.EventType.signature_request_downloadable
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_74]
	at com.hellosign.sdk.resource.support.types.EventType.valueOf(EventType.java:27) ~[hellosign-java-sdk-4.0.2.jar:na]
	at com.hellosign.sdk.resource.Event.getType(Event.java:280) ~[hellosign-java-sdk-4.0.2.jar:na]
	at com.hellosign.sdk.resource.Event.<init>(Event.java:73) ~[hellosign-java-sdk-4.0.2.jar:na]
	at com.hubspot.partnerdb.service.resources.v1.HelloSignWebhookResource.handleEventCallback(HelloSignWebhookResource.java:57) ~[PartnerDbService-1.0-SNAPSHOT.jar:na]
	at com.yammer.metrics.guice.TimedInterceptor.lambda$forMethodSync$0(TimedInterceptor.java:42) ~[metrics-guice-1.0-hubspot-20161115.214657-19.jar:na]
	at sun.reflect.GeneratedMethodAccessor462.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
```

**Comment by cmpaul** [comment]
@mveitas Yes, definitely update to 4.0.3 when possible. I've made changes to the SDK to avoid this throwing the above exception when this occurs in the future. Apologies for any inconvenience!
